apiVersion: v1
kind: Pod
metadata:
  name: minio-client
  labels:
    app: minio-client
spec:
  containers:
  - name: minio-client
    image: minio/mc:latest
    imagePullPolicy: IfNotPresent
    command: ["/test/test-minio.sh"]
    volumeMounts:
      - name: test-minio
        mountPath: "/test"
  volumes:
    - name: test-minio
      configMap:
        name: test-minio
        defaultMode: 0745
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-minio
data:
  test-minio.sh: |
    #!/bin/sh
    mc
    # If TLS is not enabled use the following URL:
    mc config host add bigtop-minio http://bigtop-minio.bigtop.svc.cluster.local:9000 minio minio123 S3v4
    # If TLS is enabled for minio service, use the following URL. If certificate is self signed user --insecure
    # mc config host add bigtop-minio https://<Minio Service Name>:9000 <ACCESSKEY>  <SECRETKEY> S3v4 --insecure
    sleep 3600
